services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build: ./frontend_gym
    ports:
      - 5173:5173
    depends_on:
      - backend
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_gym
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    
volumes:
  db-data: